- block:
      - name: delete report file if present
        file:
          path: /tmp/aws_usecase_report.csv
          state: absent
        delegate_to: localhost
        
      
      - name: create csv header file
        lineinfile:
          path: /tmp/aws_usecase_report.csv
          line: VM Name, VM ID, VPC ID, PUBLIC IP, SECURITY GROUP ID, SUBNET ID, PRIVATE IP
          create: yes
        delegate_to: localhost
      
        
      - name: append data into the file
        lineinfile:
          path: /tmp/aws_usecase_report.csv
          line: |
            {{ stat_vm_name }}, {{ stat_vm_id }}, {{ stat_vpc_id }}, {{ stat_public_ip }}, {{stat_security_group_id}}, {{stat_subnet_id}}, {{stat_private_ip}}
          state: present
        delegate_to: localhost

  rescue:
      - name: Display error message
        debug: msg="Error in parsing the query"
      
      - name: End the play for hosts 
        meta: end_host

- block:
      - name: Sending aws report mail
        mail:
          host: smtp.gmail.com
          port: 587
          username: "{{var_mail_username}}"
          password: "{{var_mail_passoword}}"
          to:
          - Omprakash Sharma <omprakash.sharma@gslab.com>
          subject: aws Resource Report
          body:
          - aws resource report
          attach:
          - /tmp/aws_usecase_report.csv
          
        delegate_to: localhost

      
  #   rescue:
  #     - name: Print Error for sending mail
  #       debug: msg="Sending mail failed"
